# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  host: ec2-54-163-238-215.compute-1.amazonaws.com
  username: nuicschlmlccep
  database: d866eepmurc3q0
  password: Uw0ugjnmJeKowJD-I1ddWSQJ6o
  port: 5432
test:
  adapter: postgresql
  database: twiter_test
  pool: 5
  timeout: 5000

production:
adapter: postgresql
host: ec2-54-163-238-215.compute-1.amazonaws.com
username: nuicschlmlccep
database: d866eepmurc3q0
password: Uw0ugjnmJeKowJD-I1ddWSQJ6o
port: 5432 
