
production:
  solr:
    hostname: 139.59.147.251
    # hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: 139.59.147.251
    # hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
