
production:
  solr:
    hostname: localhost
    #hostname: 37.139.4.141
    # hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: 37.139.4.141
    port: 8983
    log_level: INFO
    path: /solr

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
